### ISSUE TITLE
Face stdout maxBuffer length exceed

### ISSUE THREAD

**Issue by gjaya79** [minhlucvan/crgpt#8]
I am using crgpt in my bitbucket pipeline. When generating the diff, I get the following error

`Error: Error: stdout maxBuffer length exceeded
    at /usr/local/lib/node_modules/crgpt/dist/lib/git.js:103:24
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)`

Any suggestion to resolve this issue?

**Comment by rayesprankle** [comment]
```
run CRGPT
sourceBranch: tensoriterator
targetBranch: main
Error: Error: stdout maxBuffer length exceeded
    at /usr/local/lib/node_modules/crgpt/dist/lib/git.js:103:24
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

same here

**Comment by minhlucvan** [comment]
added to new replease: https://www.npmjs.com/package/crgpt/v/1.2.0
